os: linux
dist: xenial
language: python

python:
 - 3.6
 - 3.7
 - 3.8
 - 3.9

#branches:
# only:
#  - main

install:
 - pip install coveralls

script:
 - coverage run --source=mizuna/ -m unittest mizuna.tests.test_mizuna

after_success:
 - coveralls

deploy:
 provider: pypi
 username: __token__
 server: https://test.pypi.org/legacy/
 distributions: sdist bdist_wheel
 skip_existing: true
 edge: true
 on:
  tags: true