version: 2.1

orbs:
  python: circleci/python@0.2.1

branches:
      only:
        - main
        - /\d+\.\d+\.\d+[a-z]*/

jobs:
  build-and-test:
    executor: python/default
    steps:
      - checkout
#       - python/load-cache
#       - python/install-deps
#       - python/save-cache
#      - run: pip install twine
      - run: pip install coveralls
      - run: coverage run --source=mizuna/ -m unittest tests.test_mizuna
#      - run: coveralls
#      - run: python setup.py sdist bdist_wheel

workflows:
  main:
    jobs:
      - build-and-test
